name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-cache

jobs:
  windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - debug
          - release
        compiler:
          - msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
        
      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Setup msvc
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Setup vcpkg
        uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: 943c5ef1c8f6b5e6ced092b242c8299caae2ff01

      - name: Build
        uses: lukka/run-cmake@v10.0
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/main/CMakeLists.txt
          configurePreset: build-${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg
          buildPreset: ${{ matrix.build-type }}-${{ matrix.compiler }}-vcpkg
